import Head from "next/head";
import { Seo } from "@/ui/component/Seo";
import { Typography } from "@/ui/design-system/typography/Typography";
import { Button } from "@/ui/design-system/button/Button";

export default function Home() {
  return (
    <>
      <Seo
        title="Mon bac à sable NextJS"
        description="Generated by create next app"
      />

      <div className="flex justify-center gap-4 p-10 ">
        <Button>Accent</Button>
        <Button size="small" variant="secondary">
          Secondary
        </Button>
        <Button size="small" variant="outline">
          outline
        </Button>
        <Button size="small" variant="disabled" disabled>
          dissabled
        </Button>
      </div>

      <div className="flex justify-center gap-4 p-10 ">
        <Button>Accent</Button>
        <Button variant="secondary">Secondary</Button>
        <Button variant="outline">outline</Button>
        <Button variant="disabled" disabled>
          dissabled
        </Button>
      </div>

      <div className="flex justify-center gap-4 p-10 ">
        <Button>Accent</Button>
        <Button size="large" variant="secondary">
          Secondary
        </Button>
        <Button size="large" variant="outline">
          outline
        </Button>
        <Button size="large" variant="disabled" disabled>
          dissabled
        </Button>
      </div>

      {/* 777 - Jackpot Man - 777 */}
      {/* <div className="space-y-5">
        <Typography theme="primary" variant="h1" component="div">
          Hello World
        </Typography>
        <Typography theme="secondary" variant="lead" component="div">
          Hello World
        </Typography>
        <Typography variant="body-sm" component="div">
          Hello World
        </Typography>
      </div> */}
    </>
  );
}
