import Head from "next/head";
import { Seo } from "@/ui/component/seo";

export default function Home() {
  return (
    <>
      <Seo
        title="Mon bac à sable NextJS"
        description="Generated by create next app"
      />
      <h1>Hello world</h1>
    </>
  );
}
