import Head from "next/head";
import { Seo } from "@/ui/component/Seo";
import { Typography } from "@/ui/design-system/typography/Typography";

export default function Home() {
  return (
    <>
      <Seo
        title="Mon bac à sable NextJS"
        description="Generated by create next app"
      />
      <div className="space-y-5">
        <Typography theme="primary" variant="h1" component="div">
          Hello World
        </Typography>
        <Typography theme="secondary" variant="lead" component="div">
          Hello World
        </Typography>
        <Typography variant="body-sm" component="div">
          Hello World
        </Typography>
      </div>
    </>
  );
}
